public class Oppurtunity {
    public static void updateDesc(List<Oppurtunity> opplist,Map<ID,Oppurtunity> oldMapList){
        List<Oppurtunity> opplisttobeUpdated=new List<Oppurtunity>();
        for (Oppurtunity opp:opplist){
             //Oppurtunity o=new Oppurtunity();
             //o.id=opp.id;
            /*if(opp.stageName!=oldMap.get(opp.id).stageName){
                if(opp.stageName=='Closed Down'){
                    o.description='oppurtunity is close down';
                }
            }*/
        }
    }
}